namespace ReinforcementLearning
{
    public enum EEnemyInput
    {
        TotalGhouls,
        IdlingGhouls,
        GhoulsInDanger,
        HungryIdlingGhouls,
        GhoulsWithWeapons,
        AttackingGhouls,
        AttackingGhoulsWithWeapons,
        DefendingGhouls,
        GhoulsInWorkshops,
        DefendingGhoulsWithWeapons,
        IdlingGhoulsWithWeapon,
        IdlingGhoulsNotHungry,
        UnassignedWeaponsInRangeAndNotInDanger,
        UnusedWorkshopsInRangeAndNotInDanger,
        UsedWorkshopsInRangeAndNotInDanger,
        UnassignedFoodsInRangeAndNotInDanger,
        UnfinishedTribesInRangeAndNotInDanger,
        UnfinishedWorkshopsInRangeAndNotInDanger,
        TribesDefensive,
        TribesAggresive,
        Churches,
        UnbalancedTribes,
        BuildingTribeGhouls,
        BuildingWorkshopGhouls,
    }
}
